### ISSUE TITLE
keymaps have no `desc`

### ISSUE THREAD

**Issue by dlyongemallo** [Wansmer/sibling-swap.nvim#18]
I use [WhichKey](https://github.com/folke/which-key.nvim) and there doesn't seem to be a way to use `sibling-swap`'s `keymaps` to set the `desc` field which is normally set when using `vim.keymap.set`.

This is what I see in WhichKey for those keys (e.g., following `<Leader>s`):
![image](https://github.com/user-attachments/assets/4a4a7396-effc-40eb-be20-adcef3690cb5)

It'd be perfectly fine to set them by default to the values of the functions which are called, e.g., `l -> swap_with_right` and so on. I just want a hint as to what those keys do in that context.

**Comment by Wansmer** [comment]
Done in #19

**Comment by dlyongemallo** [comment]
Awesome! Thanks so much!

![image](https://github.com/user-attachments/assets/6f14b3a6-f62b-480a-9961-3b1960efd978)
